---
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height = 3, fig.width = 6)

library(dplyr)
library(ggplot2)
library(waffle)
library(forcats)
library(sf)
library(here)
library(patchwork)

# darkgoldenrod
# "#B8860B" "#EEAD0E"

uk_prod <- "#8B4513" 
uk_exp <- "#D2691E" 
uk_imp <- "#838B83" 
  # "#EEE8CD" "#CD950C"
  
# "#8B6508" "#8B7E66" "#CDC8B1"
```


```{r uk-map}


uk_tiles <- st_read(here("data", "maps", "tilegrams", "uk_tilegram.shp"), quiet = TRUE)
world_tiles <- st_read(here("data", "maps", "tilegrams", "world_tilegram.shp"), quiet = TRUE)


uk_map <- ggplot(uk_tiles) +
  geom_sf(fill = uk_prod, colour = "white", lwd = 0.5) +
  # annotation_custom(grob = grid::circleGrob(r = 0.5, gp = grid::gpar(fill = NA))) +
  theme_void() 
```


```{r world-map, fig.height=1.5, fig.width=3}
world_map <- ggplot(world_tiles) +
  geom_sf(fill = uk_imp, colour = "white", lwd = 0.5) +
  theme_void() 

export_map <- ggplot(world_tiles) +
  geom_sf(fill = alpha(uk_exp, 0.2), colour = alpha(uk_exp,0.2), lwd = 0.5) +
  theme_void() 

import_map <- ggplot(world_tiles) +
  geom_sf(fill = alpha(uk_imp,0.2), colour = alpha(uk_imp,0.2), lwd = 0.5) +
  theme_void()

```







```{r uk-production, fig.height=3, fig.width=9}


prod <- tibble(type = c("domestic", "exports", "imports" ), vol = c(86, 14, 62))

uk_production <- prod |> 
  ggplot() + 
  geom_waffle(aes(fill = type, values = vol),n_rows = 10, colour = "white", size = 1) + 
  scale_fill_manual(
    values = c(uk_prod, uk_prod, "white")
  ) +
  theme_void() +
  theme(legend.position = "none") +
  # labs(title = "UK production") +
  annotate("text", x = 14, y = 5.5, label = "Total UK Domestic \nproduction")

title <- "UK \nProduction"
uk <- uk_map +
annotate("text", x = 300000, y = 600000, label = title, fontface = "bold", size = 6)

# wrap_elements(grid::textGrob(title, vjust = -1, gp = grid::gpar(fontface = "bold", fontsize = 16))) + 
#   uk_map + 
  uk +
  uk_production + 
  plot_layout(widths = c(1,4))

```




```{r uk-exports, fig.height=3, fig.width=9}
uk_exports <- prod |> 
  ggplot() + 
  geom_waffle(aes(fill = type, values = vol),n_rows = 10, colour = "white", size = 1) + 
  scale_fill_manual(values = c(uk_prod, uk_exp, "white")) +

  theme_void() +
  theme(legend.position = "none") +
  annotate("text", x = 14, y = 5.5, label = "Some UK production \nis exported")

title <- "UK\nProduction\navailable for\nconsumption"
uk <- uk_map +
annotate("text", x = 350000, y = 600000, label = title, fontface = "bold", size = 6)

# wrap_elements(grid::textGrob(title, vjust = 0, gp = grid::gpar(fontface = "bold", fontsize = 16))) + 
#   uk_map + 
  uk +
  uk_exports + 
  inset_element(export_map, left = 0.6, bottom = 0.5, right =1, top = 1, on_top = TRUE, align_to = "full") +
  plot_layout(widths = c(1,4))
```




```{r supply, fig.height=3, fig.width=10}
supply <- tibble(type = c("domestic", "imports", "exports"), vol = c(86, 62, 14)) 

uk_supply <- supply |>
  ggplot() + 
  geom_waffle(aes(fill = type, values = vol),n_rows = 10, colour = "white",size = 1) + 
  scale_fill_manual(values = c(uk_prod, alpha(uk_exp,0.1),uk_imp)) +
  theme_void() +
  theme(legend.position = "none") +
  labs(title = "58% of the food we eat comes from the UK") +
  theme(plot.title = element_text(hjust = 0.12), plot.title.position = "panel")

title <- "UK \nSupply \n= \nUK \nConsumption"
uk <- uk_map +
annotate("text", x = 350000, y = 600000, label = title, fontface = "bold", size = 5)

 # wrap_elements(grid::textGrob(title, vjust = 0.2, gp = grid::gpar(fontface = "bold", fontsize = 16))) + 
 #  uk_map + 
  uk +
  uk_supply + 
  grid::textGrob("42% of \nconsumption \nis imported\n(exports are \nnot included)", vjust = 0.2) + 
  plot_layout(widths = c(1,3,1)) +
  # inset_element(export_map, left = 0, bottom = 0.5, right =1, top = 1, on_top = TRUE, align_to = "full") +
  inset_element(import_map, left = 0, bottom = 0, right =1, top = 0.5, on_top = TRUE, align_to = "full")
```




```{r psp, fig.height=3, fig.width=10}
psp <- tibble(type = c("domestic", "exports", "imports" ), vol = c(86, 14, 62))

uk_psp <- psp |>
  ggplot() + 
  geom_waffle(aes(fill = type, values = vol),n_rows = 10, colour = "white", size = 1) + 
  scale_fill_manual(
    values = c(uk_prod, uk_exp, uk_imp)
  ) +
  theme_void() +
  theme(legend.position = "none") +
  labs(title = "UK production is 61% of total supply") +
  theme(plot.title = element_text(hjust = 0.1), plot.title.position = "panel")

title <- "Production\nto Supply\nratio"

uk <- uk_map +
annotate("text", x = 300000, y = 600000, label = title, fontface = "bold", size = 6)

  # wrap_elements(grid::textGrob(title, vjust = -0.4, gp = grid::gpar(fontface = "bold", fontsize = 16))) + 
  # uk_map + 
  uk +
  uk_psp + 
  grid::textGrob("UK production\n(including exports) \ncompared to \noverall supply\n is a proxy for\n'self-sufficiency'",vjust = 0.5) + 
  plot_layout(widths = c(1,3,1)) 
  # inset_element(export_map, left = 0, bottom = 0, right =1, top = 0.5, on_top = TRUE, align_to = "full")

```





```{r test, fig.height=3, fig.width=10}

x <- uk_map +
annotate("text", x = 300000, y = 600000, label = "Production\nto Supply\nratio", fontface = "bold", size = 6)

 # x +
 # uk_psp + 
 #  grid::textGrob("UK production\n(including exports) \ncompared to \noverall supply",vjust = -0.1) + 
 #  plot_layout(widths = c(1,3,1)) +
 #  inset_element(export_map, left = 0, bottom = 0, right =1, top = 0.5, on_top = TRUE, align_to = "full")

```